### ISSUE TITLE
[REQUEST] Rule element in documents

### ISSUE THREAD

**Issue by maximechareyron** [lukasbach/yana#11]
Hello Lukas,
I love your app !

Is is possible to add a "rule" element in the text editor ?
(similar to \<hr\> balise in html, or "---" in markdown, for example).

---

Thanks a lot

**Comment by lukasbach** [comment]
Hi, thank you for your suggestion! Good idea, I'll add that feature in the next release.

**Comment by lukasbach** [comment]
Added in v1.0.7! Insert ``---`` into the editor to add a divider, or click on the plus icon in the editor, then on "Divider".
