### ISSUE TITLE
Preview

### ISSUE THREAD

**Issue by godreamgo** [lukasbach/yana#12]
How can I preview the text I have created?

I'm sorry that I'm not good at English, but I'm sure you can understand it.

**Comment by lukasbach** [comment]
Hi! I'm no sure if I understand how you imagine a preview feature. You currently write notes in the app, you can just view the content by opening the note. Are you thinking of some kind of exporting feature?

**Comment by godreamgo** [comment]
I apologize for the poor explanation.

I wanted to ask how to embed the CodePen snippet, since it doesn't show up when I embed it.

Thank you very much for your reply.

**Comment by lukasbach** [comment]
I'm still not sure if I understand. CodePen is a different service, do you mean the code snippets that you can create within Yana? Where do you want to embed the snippet?

**Comment by godreamgo** [comment]
I can't explain it well, so I'm done with this one. 
Thank you very much.
