### ISSUE TITLE
[REQUEST] gave an option to hide the note header or edit its margins

### ISSUE THREAD

**Issue by badrelmers** [lukasbach/yana#2]
**Is your feature request related to a problem? Please describe.**
actually Yana eats a lot of space in the header (about 20% of the page), this make the markdown note difficult to read/use

**Describe the solution you'd like**
is it possible to gave us an option to change the header margins, or an option to hide it completely and leave only the WYSIWYG menu?

**Additional context**
this is how it actually looks
![image](https://user-images.githubusercontent.com/40046489/100403567-89fcbb00-305f-11eb-9940-521505e2f982.png)
 
I hope I can make it like that:
![image](https://user-images.githubusercontent.com/40046489/100403943-7aca3d00-3060-11eb-8934-735cc94d9fc0.png)

Thank you.

**Comment by lukasbach** [comment]
Great suggestion, I've just deployed a new version where the header can be collapsed into a smaller state. Thanks for the idea!

I've just noticed the app bar icons (close icon, minimize... on the top right) are not properly showing on your side. Could you kindly share your OS and version (e.g. Windows 10) so I can look into that?

**Comment by badrelmers** [comment]
I just tested the new version; it is a lot better now , thank you very very much.

> I've just noticed the app bar icons (close icon, minimize... on the top right) are not properly showing on your side. 

yes.
I m using win 7 sp1.

**Comment by lukasbach** [comment]
Ok thanks for the info!
