### ISSUE TITLE
[BUG] Image & hyperlink adding issue

### ISSUE THREAD

**Issue by Pranaviate** [lukasbach/yana#20]
The image adding feature does not work for me properly as of now.
Apart from that I am not able to create a hyperlink in the app

**Comment by lukasbach** [comment]
Hi, thanks for your feedback!

Image adding currently is an alpha-feature and might not work as expected.
Hyperlink creation via the button or hotkey indeed does not work, I can confirm. I'll look into that. What should work though is just pasting an existing URL into the app, that way you should still get a clickable link in your note.

**Comment by foobargeez** [comment]
> What should work though is just pasting an existing URL into the app, that way you should still get a clickable link in your note

Thanks for the workaround - able to paste URL and then edit the text.

**Comment by lukasbach** [comment]
The hyperlink button in the note editor is now fixed should work as intended in Yana 1.0.10.

Image adding is already tracked by #15, so I'll close this.
