### ISSUE TITLE
Cannot install on Debian 11, dependency failed

### ISSUE THREAD

**Issue by saudiqbal** [lukasbach/yana#29]
keep getting the error when installing deb file, dependency failed.

**Comment by saudiqbal** [comment]
This is what I get when I do an install
yana : Depends: libappindicator3-1 but it is not installable

**Comment by lukasbach** [comment]
Hi @saudiqbal, thank you for your report. Can you try this solution and see if it works? https://stackoverflow.com/a/66958354/2692307

**Comment by saudiqbal** [comment]
I switched to Kubuntu and it works fine there.
