### ISSUE TITLE
About Section

### ISSUE THREAD

**Issue by sflorg** [lukasbach/yana#34]
I agree with others on "Minimize to Tray" and "Dark Mode", but I would like to add (unless I'm missing it) an "About" on the program with version and links to project. 

Project off to a good start, and found using "Dropbox" for the file location works well in keeping all rigs in sync.

**Comment by lukasbach** [comment]
Hello @sflorg, happy to hear :)

Yana has an about section, you can click on the name of your workspace (top left), and then go to "About Yana" in the dropdown. Are there links or details missing from there that you would expect there?

**Comment by sflorg** [comment]
Well, I don't know how I missed that. . . was just expecting somewhere in settings.
Wonderful program, and wishing you well this New Year. Thanks Lukas.

**Comment by lukasbach** [comment]
Thanks, you too :)
