### ISSUE TITLE
[REQUEST] Find for word feature

### ISSUE THREAD

**Issue by erbacellar** [lukasbach/yana#7]
The app lack this feature, like Notepad++ has the feature of looking for a specific word inside a document or note.

**Comment by lukasbach** [comment]
Hi @erbacellar, thank you for your suggestion! The feature was added in v1.0.7. In the editor, you'll find a lense icon to the right, that can be used to search or replace items in the current note document.

![image](https://user-images.githubusercontent.com/4140121/102122067-436fd480-3e45-11eb-904c-c779c886b82e.png)
